//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class DonHang : XPObject
    {
        string fMaDH;
        public string MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<string>(nameof(MaDH), ref fMaDH, value); }
        }
        DateTime fNgayTaoDon;
        public DateTime NgayTaoDon
        {
            get { return fNgayTaoDon; }
            set { SetPropertyValue<DateTime>(nameof(NgayTaoDon), ref fNgayTaoDon, value); }
        }
        DateTime fNgayGiaoDuKien;
        public DateTime NgayGiaoDuKien
        {
            get { return fNgayGiaoDuKien; }
            set { SetPropertyValue<DateTime>(nameof(NgayGiaoDuKien), ref fNgayGiaoDuKien, value); }
        }
        string fTrangThai;
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        NguoiDung fMaND;
        [Association(@"DonHangReferencesNguoiDung")]
        public NguoiDung MaND
        {
            get { return fMaND; }
            set { SetPropertyValue<NguoiDung>(nameof(MaND), ref fMaND, value); }
        }
        [Association(@"ChiTietDonHangReferencesDonHang")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
        public decimal TongTien
        {
            get
            {
                decimal tien = 0;
                foreach (ChiTietDonHang item in ChiTietDonHangs)
                {
                    tien += item.ThanhTien;
                }
                return tien;
            }
        }
    }

}
