//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class DonHang : XPObject
    {
        string fMaDH;
        public string MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<string>(nameof(MaDH), ref fMaDH, value); }
        }
        DateTime fNgayTaoDon;
        public DateTime NgayTaoDon
        {
            get { return fNgayTaoDon; }
            set { SetPropertyValue<DateTime>(nameof(NgayTaoDon), ref fNgayTaoDon, value); }
        }
        DateTime fNgayGiaoDuKien;
        public DateTime NgayGiaoDuKien
        {
            get { return fNgayGiaoDuKien; }
            set { SetPropertyValue<DateTime>(nameof(NgayGiaoDuKien), ref fNgayGiaoDuKien, value); }
        }
        string fTrangThai;
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        NguoiDung fMaND;
        [Association(@"DonHangReferencesNguoiDung")]
        public NguoiDung MaND
        {
            get { return fMaND; }
            set { SetPropertyValue<NguoiDung>(nameof(MaND), ref fMaND, value); }
        }
        string fDiaChiNhanHang;
        public string DiaChiNhanHang
        {
            get { return fDiaChiNhanHang; }
            set { SetPropertyValue<string>(nameof(DiaChiNhanHang), ref fDiaChiNhanHang, value); }
        }
        string fHoTen;
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        Shipper fMaShipper;
        [Association(@"DonHangReferencesShipper")]
        public Shipper MaShipper
        {
            get { return fMaShipper; }
            set { SetPropertyValue<Shipper>(nameof(MaShipper), ref fMaShipper, value); }
        }
        string fTenShipper;
        public string TenShipper
        {
            get { return fTenShipper; }
            set { SetPropertyValue<string>(nameof(TenShipper), ref fTenShipper, value); }
        }
        string fSDT_Shipper;
        public string SDT_Shipper
        {
            get { return fSDT_Shipper; }
            set { SetPropertyValue<string>(nameof(SDT_Shipper), ref fSDT_Shipper, value); }
        }
        decimal fTongTien;
        public decimal TongTien
        {
            get
            {
                decimal tien = 0;
                foreach (ChiTietDonHang item in ChiTietDonHangs)
                {
                    tien += item.ThanhTien;
                }
                return tien;
            }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        [Association(@"ChiTietDonHangReferencesDonHang")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
    }

}
