//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class KhuyenMai : XPObject
    {
        string fMaKM;
        public string MaKM
        {
            get { return fMaKM; }
            set { SetPropertyValue<string>(nameof(MaKM), ref fMaKM, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        string fMucKhuyenMai;
        public string MucKhuyenMai
        {
            get { return fMucKhuyenMai; }
            set { SetPropertyValue<string>(nameof(MucKhuyenMai), ref fMucKhuyenMai, value); }
        }
        string fDieuKienKhuyenMai;
        public string DieuKienKhuyenMai
        {
            get { return fDieuKienKhuyenMai; }
            set { SetPropertyValue<string>(nameof(DieuKienKhuyenMai), ref fDieuKienKhuyenMai, value); }
        }
        DateTime fNgayBatDau;
        public DateTime NgayBatDau
        {
            get { return fNgayBatDau; }
            set { SetPropertyValue<DateTime>(nameof(NgayBatDau), ref fNgayBatDau, value); }
        }
        DateTime fNgayKetThuc;
        public DateTime NgayKetThuc
        {
            get { return fNgayKetThuc; }
            set { SetPropertyValue<DateTime>(nameof(NgayKetThuc), ref fNgayKetThuc, value); }
        }
        [Association(@"SanPhamReferencesKhuyenMai")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
