//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class NguoiDung : XPObject
    {
        string fMaND;
        public string MaND
        {
            get { return fMaND; }
            set { SetPropertyValue<string>(nameof(MaND), ref fMaND, value); }
        }
        string fHoTen;
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fDiaChi;
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fPhanQuyen;
        public string PhanQuyen
        {
            get { return fPhanQuyen; }
            set { SetPropertyValue<string>(nameof(PhanQuyen), ref fPhanQuyen, value); }
        }
        [Association(@"DonHangReferencesNguoiDung")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
        [Association(@"DanhGiaSanPhamReferencesNguoiDung")]
        public XPCollection<DanhGiaSanPham> DanhGiaSanPhams { get { return GetCollection<DanhGiaSanPham>(nameof(DanhGiaSanPhams)); } }
    }

}
