//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class SanPham : XPObject
    {
        string fMaSP;
        public string MaSP
        {
            get { return fMaSP; }
            set { SetPropertyValue<string>(nameof(MaSP), ref fMaSP, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        decimal fGia;
        public decimal Gia
        {
            get { return fGia; }
            set { SetPropertyValue<decimal>(nameof(Gia), ref fGia, value); }
        }
        string fHinhAnh;
        public string HinhAnh
        {
            get { return fHinhAnh; }
            set { SetPropertyValue<string>(nameof(HinhAnh), ref fHinhAnh, value); }
        }
        string fSoLuongTon;
        public string SoLuongTon
        {
            get { return fSoLuongTon; }
            set { SetPropertyValue<string>(nameof(SoLuongTon), ref fSoLuongTon, value); }
        }
        DanhMuc fMaDM;
        [Association(@"SanPhamReferencesDanhMuc")]
        public DanhMuc MaDM
        {
            get { return fMaDM; }
            set { SetPropertyValue<DanhMuc>(nameof(MaDM), ref fMaDM, value); }
        }
        NhaCC fMaNCC;
        [Association(@"SanPhamReferencesNhaCC")]
        public NhaCC MaNCC
        {
            get { return fMaNCC; }
            set { SetPropertyValue<NhaCC>(nameof(MaNCC), ref fMaNCC, value); }
        }
        KhuyenMai fMaKM;
        [Association(@"SanPhamReferencesKhuyenMai")]
        public KhuyenMai MaKM
        {
            get { return fMaKM; }
            set { SetPropertyValue<KhuyenMai>(nameof(MaKM), ref fMaKM, value); }
        }
        [Association(@"DanhGiaSanPhamReferencesSanPham")]
        public XPCollection<DanhGiaSanPham> DanhGiaSanPhams { get { return GetCollection<DanhGiaSanPham>(nameof(DanhGiaSanPhams)); } }
        [Association(@"ChiTietDonHangReferencesSanPham")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
    }

}
