//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CS403_SK.Module.BusinessObjects.ORMDataModel1
{

    public partial class Shipper : XPObject
    {
        string fMaShipper;
        public string MaShipper
        {
            get { return fMaShipper; }
            set { SetPropertyValue<string>(nameof(MaShipper), ref fMaShipper, value); }
        }
        string fTenShipper;
        public string TenShipper
        {
            get { return fTenShipper; }
            set { SetPropertyValue<string>(nameof(TenShipper), ref fTenShipper, value); }
        }
        string fDiaChi_Shipper;
        public string DiaChi_Shipper
        {
            get { return fDiaChi_Shipper; }
            set { SetPropertyValue<string>(nameof(DiaChi_Shipper), ref fDiaChi_Shipper, value); }
        }
        string fSDT_Shipper;
        public string SDT_Shipper
        {
            get { return fSDT_Shipper; }
            set { SetPropertyValue<string>(nameof(SDT_Shipper), ref fSDT_Shipper, value); }
        }
        [Association(@"DonHangReferencesShipper")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
